# Generated by Django 5.2.6 on 2025-09-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_sticker_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('font_file', models.URLField(max_length=500)),
                ('font_format', models.CharField(choices=[('truetype', 'TTF'), ('opentype', 'OTF'), ('woff', 'WOFF'), ('woff2', 'WOFF2')], default='opentype', max_length=20)),
                ('font_weight', models.CharField(default='normal', max_length=20)),
                ('font_style', models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic'), ('oblique', 'Oblique')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fonts',
            },
        ),
    ]
