# Generated by Django 5.2.6 on 2025-09-25 05:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='font_file',
            field=models.FileField(upload_to=blog.models.font_upload_path),
        ),
    ]
